# OUTPUT_LANG_INDEX start from 0
generator-localization-test-language:
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=3 SPREADSHEET_ID=1_x_-cEiMi_YlH-m5WL2qlMtIvXpz-7SPxbSaIt6m9cI GID_ID=test-language OUTPUT_FOLDER=../public/locales/en/common.json
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=4 SPREADSHEET_ID=1_x_-cEiMi_YlH-m5WL2qlMtIvXpz-7SPxbSaIt6m9cI GID_ID=test-language OUTPUT_FOLDER=../public/locales/vi/common.json

